---
title: "ELISA assignment Analysis"
author: "Berhe"
date: "`r Sys.Date()`"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(rio, 
               here, 
               tidyverse,
               gtsummary)

```



```{r import the different plates}
# import data with the raw reading---------------------------------------------
patient1 <- import(("Appendix 2.xlsx"), sheet = "Patient 1") %>% 
  # add a patient column 
  mutate(patient = "Patient 1") %>% 
   rename(naive_sera_control = 11) %>% 
  select(11, patient) %>% 
  mutate( group = c("ab1", "ab1", "ab2", "ab2", "ab3", "ab3", "ab4", "ab4")) %>% 
  group_by(group, patient) %>% 
  summarise(mean_ab_naive_s = mean(naive_sera_control, na.rm = T))



patient2 <- import(("Appendix 2.xlsx"), sheet = "Patient 2") %>% 
  # add a patient column 
  mutate(patient = "Patient 2") %>% 
  rename(naive_sera_control = 11) %>% 
  select(11, patient) %>% 
  mutate( group = c("ab1", "ab1", "ab2", "ab2", "ab3", "ab3", "ab4", "ab4")) %>% 
  group_by(group, patient) %>% 
  summarise(mean_ab_naive_s = mean(naive_sera_control, na.rm = T))

patient3 <- import(("Appendix 2.xlsx"), sheet = "Patient 3") %>% 
  # add a patient column 
  mutate(patient = "Patient 3") %>% 
  rename(naive_sera_control = 11) %>% 
  select(11, patient) %>% 
  mutate( group = c("ab1", "ab1", "ab2", "ab2", "ab3", "ab3", "ab4", "ab4")) %>% 
  group_by(group, patient) %>% 
  summarise(mean_ab_naive_s = mean(naive_sera_control, na.rm = T))

patient4 <- import(("Appendix 2.xlsx"), sheet = "Patient 4") %>% 
  # add a patient column 
  mutate(patient = "Patient 4") %>% 
  rename(naive_sera_control = 11) %>% 
  select(11, patient) %>% 
  mutate( group = c("ab1", "ab1", "ab2", "ab2", "ab3", "ab3", "ab4", "ab4")) %>% 
  group_by(group, patient) %>% 
  summarise(mean_ab_naive_s = mean(naive_sera_control, na.rm = T))

patient5 <- import(("Appendix 2.xlsx"), sheet = "Patient 5") %>% 
  # add a patient column 
  mutate(patient = "Patient 5") %>% 
  rename(naive_sera_control = 11) %>% 
  select(11, patient) %>% 
  mutate( group = c("ab1", "ab1", "ab2", "ab2", "ab3", "ab3", "ab4", "ab4")) %>% 
  group_by(group, patient) %>% 
  summarise(mean_ab_naive_s = mean(naive_sera_control, na.rm = T))


# bind the rows

patients_naive_sera <- bind_rows(patient1, patient2, patient3, patient4, patient5) %>% 
  rename(patient = patient,
         Antibody = group) %>% 
  mutate(Antibody = recode(Antibody,
                           "ab1" = "Antibody 1",
                           "ab2" = "Antibody 2",
                           "ab3" = "Antibody 3",
                           "ab4" = "Antibody 4")) %>% 
  mutate(mean_ab_naive_s = log(mean_ab_naive_s))

```


```{r clean the florsence stage }


patient_1_raw <- import(("Appendix 2.xlsx"), sheet = "Patient 1") %>% 
  
  # add a patient column 
  mutate(patient = "Patient 1") %>% 
  
  # add the dilution column
  mutate(dilution = c(0.10, 0.02, 0.004, 0.0008, 0.00016,0.000032,0.0000064,0)) %>% 
  
  # rename the columns 
  rename(Ab1_R1 = 3, Ab1_R2 = 4,  Ab2_R1 = 5, Ab2_R2 = 6,
         Ab3_R1 = 7, Ab3_R2 = 8, Ab4_R1 = 9,
         Ab4_R2 = 10, `PBS (-ve control)` = 2,
         plate = 1) %>% 
  
  # group row wise 
  rowwise() %>% 
  
  # calculate the average 
  mutate(
    Average_Ab1 = mean(Ab1_R1,Ab1_R2, na.rm = T),
    Average_Ab2 = mean(Ab2_R1,Ab2_R2, na.rm = T),
    Average_Ab3 = mean(Ab3_R1,Ab3_R2, na.rm = T),
    Average_Ab4 = mean(Ab4_R1,Ab4_R2, na.rm = T)) %>% 
  select(Average_Ab1,
         Average_Ab2,
         Average_Ab3,
         Average_Ab4,
         `PBS (-ve control)`,
         dilution,
         patient 
        )


patient_2_raw <- import(("Appendix 2.xlsx"), sheet = "Patient 2") %>%
  
  mutate(patient = "Patient 2") %>% 
  mutate(dilution = c(0.10, 0.02, 0.004, 0.0008, 0.00016,0.000032,0.0000064,0)) %>% 
  rename(Ab1_R1 = 3, Ab1_R2 = 4,  Ab2_R1 = 5, Ab2_R2 = 6,
         Ab3_R1 = 7, Ab3_R2 = 8, Ab4_R1 = 9,
         Ab4_R2 = 10, `PBS (-ve control)` = 2,
         plate = 1) %>% 
  rowwise() %>% 
  mutate(
    Average_Ab1 = mean(Ab1_R1,Ab1_R2, na.rm = T),
    Average_Ab2 = mean(Ab2_R1,Ab2_R2, na.rm = T),
    Average_Ab3 = mean(Ab3_R1,Ab3_R2, na.rm = T),
    Average_Ab4 = mean(Ab4_R1,Ab4_R2, na.rm = T)) %>% 
  select(Average_Ab1,
         Average_Ab2,
         Average_Ab3,
         Average_Ab4,
         `PBS (-ve control)`,
         dilution,
         patient 
        )


patient_3_raw <- import(("Appendix 2.xlsx"), sheet = "Patient 3") %>%
  mutate(patient = "Patient 3") %>% 
  mutate(dilution = c(0.10, 0.02, 0.004, 0.0008, 0.00016,0.000032,0.0000064,0)) %>% 
  rename(Ab1_R1 = 3, Ab1_R2 = 4,  Ab2_R1 = 5, Ab2_R2 = 6,
         Ab3_R1 = 7, Ab3_R2 = 8, Ab4_R1 = 9,
         Ab4_R2 = 10, `PBS (-ve control)` = 2, 
         plate = 1) %>% 
  rowwise() %>% 
  mutate(
    Average_Ab1 = mean(Ab1_R1,Ab1_R2, na.rm = T),
    Average_Ab2 = mean(Ab2_R1,Ab2_R2, na.rm = T),
    Average_Ab3 = mean(Ab3_R1,Ab3_R2, na.rm = T),
    Average_Ab4 = mean(Ab4_R1,Ab4_R2, na.rm = T)) %>% 
  select(Average_Ab1,
         Average_Ab2,
         Average_Ab3,
         Average_Ab4,
         `PBS (-ve control)`,
         dilution,
         patient 
        )


patient_4_raw <- import(("Appendix 2.xlsx"), sheet = "Patient 4") %>%
  mutate(patient = "Patient 4") %>% 
  mutate(dilution = c(0.10, 0.02, 0.004, 0.0008, 0.00016,0.000032,0.0000064,0)) %>% 
  rename(Ab1_R1 = 3, Ab1_R2 = 4,  Ab2_R1 = 5, Ab2_R2 = 6, 
         Ab3_R1 = 7, Ab3_R2 = 8, Ab4_R1 = 9,
         Ab4_R2 = 10, `PBS (-ve control)` = 2,
         plate = 1) %>% 
  rowwise() %>% 
  mutate(
    Average_Ab1 = mean(Ab1_R1,Ab1_R2, na.rm = T),
    Average_Ab2 = mean(Ab2_R1,Ab2_R2, na.rm = T),
    Average_Ab3 = mean(Ab3_R1,Ab3_R2, na.rm = T),
    Average_Ab4 = mean(Ab4_R1,Ab4_R2, na.rm = T)) %>% 
  select(Average_Ab1,
         Average_Ab2,
         Average_Ab3,
         Average_Ab4,
         `PBS (-ve control)`,
         dilution,
         patient 
        )


patient_5_raw <- import(("Appendix 2.xlsx"), sheet = "Patient 5") %>%
  mutate(patient = "Patient 5") %>% 
  mutate(dilution = c(0.10, 0.02, 0.004, 0.0008, 0.00016,0.000032,0.0000064,0)) %>% 
  rename(Ab1_R1 = 3, Ab1_R2 = 4,  Ab2_R1 = 5, Ab2_R2 = 6,
         Ab3_R1 = 7, Ab3_R2 = 8, Ab4_R1 = 9,
         Ab4_R2 = 10, `PBS (-ve control)` = 2, 
         plate = 1) %>% 
  rowwise() %>% 
  mutate(
    Average_Ab1 = mean(Ab1_R1,Ab1_R2, na.rm = T),
    Average_Ab2 = mean(Ab2_R1,Ab2_R2, na.rm = T),
    Average_Ab3 = mean(Ab3_R1,Ab3_R2, na.rm = T),
    Average_Ab4 = mean(Ab4_R1,Ab4_R2, na.rm = T)) %>% 
  select(Average_Ab1,
         Average_Ab2,
         Average_Ab3,
         Average_Ab4,
         `PBS (-ve control)`,
         dilution,
         patient 
        )
patient_1_raw
patient_2_raw
patient_3_raw
patient_4_raw
patient_5_raw
```

<!-- Calculate the difference between the blank control and the photo spectrometer reading --->

```{r }
p1_mean_diff <- patient_1_raw %>% 
rowwise() %>% 
  mutate(redu_av_Ab1 = 0.2112 - Average_Ab1,
         redu_av_Ab2 = 0.2034 - Average_Ab2,
         redu_av_Ab3 = 0.2502 - Average_Ab3,
         redu_av_Ab4 = 0.2142 - Average_Ab4) %>% 
  select(redu_av_Ab1, redu_av_Ab2, redu_av_Ab3, redu_av_Ab4, patient, dilution,  `PBS (-ve control)`)


p2_mean_diff <- patient_2_raw %>% 
rowwise() %>% 
  mutate(redu_av_Ab1 = 0.2605 - Average_Ab1,
         redu_av_Ab2 = 0.2769 - Average_Ab2,
         redu_av_Ab3 = 0.4411 - Average_Ab3,
         redu_av_Ab4 = 0.2638 - Average_Ab4) %>% 
  select(redu_av_Ab1, redu_av_Ab2, redu_av_Ab3, redu_av_Ab4, patient,dilution,  `PBS (-ve control)`)


p3_mean_diff <- patient_3_raw %>% 
rowwise() %>% 
  mutate(redu_av_Ab1 = 0.2036 - Average_Ab1,
         redu_av_Ab2 = 0.2104 - Average_Ab2,
         redu_av_Ab3 = 0.2058 - Average_Ab3,
         redu_av_Ab4 = 0.2059 - Average_Ab4) %>% 
  select(redu_av_Ab1, redu_av_Ab2, redu_av_Ab3, redu_av_Ab4, patient, dilution,  `PBS (-ve control)`)

p4_mean_diff <- patient_4_raw %>% 
rowwise() %>% 
  mutate(redu_av_Ab1 = 0.2180 - Average_Ab1,
         redu_av_Ab2 = 0.2003 - Average_Ab2,
         redu_av_Ab3 = 0.1999 - Average_Ab3,
         redu_av_Ab4 = 0.1996 - Average_Ab4) %>% 
  select(redu_av_Ab1, redu_av_Ab2, redu_av_Ab3, redu_av_Ab4, patient, dilution, `PBS (-ve control)`)


p5_mean_diff <- patient_5_raw %>% 
rowwise() %>% 
  mutate(redu_av_Ab1 = 0.2407 - Average_Ab1,
         redu_av_Ab2 = 0.1949 - Average_Ab2,
         redu_av_Ab3 = 0.2124 - Average_Ab3,
         redu_av_Ab4 = 0.2025 - Average_Ab4) %>% 
  select(redu_av_Ab1, redu_av_Ab2, redu_av_Ab3, redu_av_Ab4, patient, dilution, `PBS (-ve control)`)



p1_mean_diff
p2_mean_diff
p3_mean_diff
p5_mean_diff
p5_mean_diff

```




 <!-- ELISA corrected for non specific binding Binding raws-------------->
 

```{r  create the long dataset}
elisa_red_av <- bind_rows(p1_mean_diff, 
                          p2_mean_diff, 
                          p3_mean_diff, 
                          p4_mean_diff, 
                          p5_mean_diff) %>% 
  mutate(dilution = format(dilution,scientific = FALSE)) %>% 
  mutate(dilution = as.numeric(dilution)) %>% 
  select(redu_av_Ab1,
         redu_av_Ab2,
         redu_av_Ab3,
         redu_av_Ab4,
         `PBS (-ve control)`,
         dilution,
         patient 
        )
elisa_red_av
```

<!----ELISA not corrected for nonspecific binding----> 

```{r}
elisa_raw <- bind_rows(patient_1_raw, 
                      patient_2_raw, 
                      patient_3_raw, 
                      patient_4_raw, 
                      patient_5_raw) %>% 
  mutate(dilution = format(dilution,scientific = FALSE)) %>% 
  mutate(dilution = as.numeric(dilution)) %>% 
  select(Average_Ab1,
         Average_Ab2,
         Average_Ab3,
         Average_Ab4,
         `PBS (-ve control)`,
         dilution,
         patient 
        )

elisa_raw

```

 <!-- Create the long data set  ----------------------------------------------- -->

```{r visualise the}

elisa <- elisa_raw %>% 
  mutate(dilution = log(dilution)) %>% 
  pivot_longer(
    cols = c(Average_Ab1:`PBS (-ve control)`),
    names_to = "Antibody",
    values_to = "Absorbtion"
  ) %>% 
  mutate(Absorbtion = log(Absorbtion)) %>% 
  mutate(Antibody = recode(Antibody,
                           "Average_Ab1" = "Antibody 1",
                           "Average_Ab2" = "Antibody 2", 
                           "Average_Ab3" = "Antibody 3", 
                           "Average_Ab4" = "Antibody 4" 
  )) %>% 
  mutate(identity_combined = paste(patient, Antibody))

# create the background noise for the standard (row-H)------------------- 

Background_noise <- elisa %>% 
  filter(dilution == -Inf & Antibody != "PBS (-ve control)") %>% 
  mutate(identity_combined = paste(patient, Antibody))


elisa
```


```{r convert the values to log base for corrected value}

# ELISA corrected------------------------------

elisa_corrected <- elisa_red_av %>% 
  mutate(dilution = log10(dilution)) %>% 
  pivot_longer(
    cols = c(redu_av_Ab1:`PBS (-ve control)`),
    names_to = "Antibody",
    values_to = "Absorbtion"
  ) %>% 
  mutate(Absorbtion = log10(Absorbtion)) 
  # mutate(Antibody = recode(Antibody,
  #                          "Average_Ab1" = "Antibody 1",
  #                          "Average_Ab2" = "Antibody 2", 
  #                          "Average_Ab3" = "Antibody 3", 
  #                          "Average_Ab4" = "Antibody 4" 
  # )) %>% 
  # mutate(identity_combined = paste(patient, Antibody))


```


<!-- Visualize your data  -->


```{r  visualise the data}
# Display background noise ------------------------------------------------

elisa %>% 
  filter(dilution != -Inf) %>% 
  ggplot(aes(x = dilution,
             y = Absorbtion,
             color = Antibody)) +
  geom_point() +
  geom_line(size = 1.0) +
  
  # set the breaks accordsing to the natural log value of the concentartion
  
  scale_x_continuous(breaks = c(-11.9, -10.3, -8.7, -7.1, -5.5,-3.9,-2.3)) +
  
  facet_wrap(~patient,
             scales = "free",
             ncol = 2) +
  labs(y = "The log of average spectrophotmeter reading for each antibody",
       x = "The log of dilution (from dilution factor 1/156,250 to 1/10)",
       title = "Indirect sandwich ELISA test of four different antibodies to diagnose DENV-3 from patient sera sample",
       subtitle = "**Scales are in natural logarithmic scale **not base10**",
       fill = "Antibody",
       caption = "The photospectometer reading and the \n 
       dilution factor are changed in to base log values \n
       from -11.9 (1/156250) to -2.3 (1/10) in the x axis, \n
       and from -1.6 (0.1946) to 0.5 (1.5995) in the y axis") +
  theme(axis.title = element_text(size = 12, face = "italic", color = "blue"),
        plot.title = element_text(size = 12, face = "bold", color = "red"),
        plot.subtitle = element_text(size = 12, face = 'italic', color = "blue"),
        strip.placement = "outside", 
        strip.text = element_text(face = "italic", color = "red", size = 10),
        plot.caption = element_text(face = "italic", color = "red"))

```

```{r join the two control data sets }
conrol_join <- left_join(Background_noise, patients_naive_sera, by = c("Antibody", "patient"))

```


```{r }
# Display background noise ------------------------------------------------

elisa %>% 
  filter(dilution != -Inf & Antibody != "PBS (-ve control)") %>% 
  ggplot(aes(x = dilution,
             y = Absorbtion,
             color = Antibody)) +
  geom_point() +
  geom_line(size = 1.0) +
  geom_hline(data = conrol_join,
            aes(yintercept = Absorbtion,lty = "Average reading for PBS + test Ab + Detection Ab")) +
  geom_hline(data = conrol_join, 
             aes(yintercept = mean_ab_naive_s,lty = "Average reading for test Ab + Naiva Sera" )) +
  scale_x_continuous(breaks = c(-11.9, -10.3, -8.7, -7.1, -5.5,-3.9,-2.3)) +
  facet_grid(Antibody~patient) +
  labs(y = "The log of average spectrophotmeter reading for each antibody",
       x = "The log of dilution (from dilution factor 1/156,250 to 1/10)",
       title = "Indirect sandwich ELISA test of four different antibodies to diagnose DENV-3 from patient sera sample",
       subtitle = "**Scales are in natural logarithmic scale **not base10**",
       fill = "Antibody",
       caption = "** The horizontal dashed lines are the balnk wells reading
       where there is no antigen added but there is PBS + capture antibody and
       secondary detection antibodies") +
  theme(axis.title = element_text(size = 12, face = "italic", color = "blue"),
        plot.title = element_text(size = 12, face = "bold", color = "red"),
        plot.subtitle = element_text(size = 12, face = 'italic', color = "blue"),
        strip.placement = "outside", 
        strip.text=element_text(face ="italic", color = "red", size = 10),
        plot.caption = element_text(face = "italic", color = "red"))
```
























